begin;

create extension if not exists pgcrypto;

create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.suppliers (
  id bigint generated by default as identity primary key,
  name text not null unique check (btrim(name) <> ''),
  created_at timestamptz not null default now()
);

create table public.materials (
  id bigint generated by default as identity primary key,
  supplier_id bigint not null references public.suppliers(id) on delete cascade,
  name text not null check (btrim(name) <> ''),
  spec text not null default '',
  unit text not null check (btrim(unit) <> ''),
  price numeric not null default 0 check (price >= 0),
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default now(),
  unique (supplier_id, name)
);

create table public.orders (
  id bigint generated by default as identity primary key,
  supplier_id bigint references public.suppliers(id) on delete set null,
  supplier_name text not null check (btrim(supplier_name) <> ''),
  items jsonb not null check (jsonb_typeof(items) = 'array'),
  user_name text not null default '',
  note text not null default '',
  request_id uuid not null default gen_random_uuid() unique,
  created_at timestamptz not null default now()
);

create index materials_supplier_sort_idx on public.materials (supplier_id, sort_order, id);
create index orders_created_at_idx on public.orders (created_at desc);

alter table public.profiles enable row level security;
alter table public.suppliers enable row level security;
alter table public.materials enable row level security;
alter table public.orders enable row level security;

-- Tables created from the SQL editor do not always inherit Supabase's API
-- grants. RLS still decides which authenticated rows are accessible.
grant usage on schema public to authenticated;
grant select, insert, update, delete on table
  public.profiles,
  public.suppliers,
  public.materials,
  public.orders
to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.current_user_is_admin()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.profiles where user_id = auth.uid() and is_admin);
$$;
revoke all on function public.current_user_is_admin() from public;
grant execute on function public.current_user_is_admin() to authenticated;

create policy "users can read own profile" on public.profiles for select to authenticated using (user_id = auth.uid());
create policy "authenticated suppliers access" on public.suppliers for all to authenticated using (true) with check (true);
create policy "authenticated materials access" on public.materials for all to authenticated using (true) with check (true);
create policy "authenticated orders access" on public.orders for all to authenticated using (true) with check (true);

create or replace function public.restore_snapshot(p_snapshot jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  v_supplier_count integer;
  v_material_count integer;
  v_order_count integer;
begin
  if auth.uid() is null then raise exception '请先登录'; end if;
  if not public.current_user_is_admin() then raise exception '只有管理员可以恢复备份'; end if;
  if p_snapshot is null or jsonb_typeof(p_snapshot) <> 'object' or p_snapshot->>'version' <> '1'
    or jsonb_typeof(p_snapshot->'suppliers') <> 'array'
    or jsonb_typeof(p_snapshot->'materials') <> 'array'
    or jsonb_typeof(p_snapshot->'orders') <> 'array'
  then raise exception '备份格式无效或版本不受支持'; end if;
  if jsonb_array_length(p_snapshot->'suppliers') > 1000
    or jsonb_array_length(p_snapshot->'materials') > 10000
    or jsonb_array_length(p_snapshot->'orders') > 100000
  then raise exception '备份记录数超过安全限制'; end if;

  if exists (select 1 from jsonb_array_elements(p_snapshot->'suppliers') s
    where jsonb_typeof(s) <> 'object' or (s->>'id') is null or btrim(coalesce(s->>'name','')) = '' or (s->>'createdAt') is null)
  then raise exception '供应商数据不完整'; end if;
  if exists (select 1 from jsonb_array_elements(p_snapshot->'materials') m
    where jsonb_typeof(m) <> 'object' or (m->>'id') is null or (m->>'supplierId') is null
      or btrim(coalesce(m->>'name','')) = '' or btrim(coalesce(m->>'unit','')) = ''
      or (m->>'price') is null or (m->>'sortOrder') is null
      or (m->>'price')::numeric < 0 or (m->>'sortOrder')::integer < 0)
  then raise exception '物料数据不完整'; end if;
  if exists (select 1 from jsonb_array_elements(p_snapshot->'orders') o
    where jsonb_typeof(o) <> 'object' or (o->>'id') is null or btrim(coalesce(o->>'supplierName','')) = ''
      or jsonb_typeof(o->'items') <> 'array' or (o->>'createdAt') is null)
  then raise exception '订单数据不完整'; end if;
  if exists (select 1 from jsonb_array_elements(p_snapshot->'materials') m where not exists (
    select 1 from jsonb_array_elements(p_snapshot->'suppliers') s where (s->>'id')::bigint = (m->>'supplierId')::bigint))
  then raise exception '存在找不到供应商的物料'; end if;

  -- Supabase's API role enables safe-update checks, so an explicit predicate is
  -- required even when the restore intentionally replaces every row.
  delete from public.orders where true;
  delete from public.materials where true;
  delete from public.suppliers where true;

  insert into public.suppliers (id,name,created_at)
    select (s->>'id')::bigint,btrim(s->>'name'),(s->>'createdAt')::timestamptz from jsonb_array_elements(p_snapshot->'suppliers') s;
  insert into public.materials (id,supplier_id,name,spec,unit,price,sort_order)
    select (m->>'id')::bigint,(m->>'supplierId')::bigint,btrim(m->>'name'),coalesce(m->>'spec',''),btrim(m->>'unit'),(m->>'price')::numeric,(m->>'sortOrder')::integer
    from jsonb_array_elements(p_snapshot->'materials') m;
  insert into public.orders (id,supplier_id,supplier_name,items,user_name,note,created_at)
    select (o->>'id')::bigint,
      case when o->'supplierId' is null or jsonb_typeof(o->'supplierId')='null' then null else (o->>'supplierId')::bigint end,
      btrim(o->>'supplierName'),o->'items',coalesce(o->>'userName',''),coalesce(o->>'note',''),(o->>'createdAt')::timestamptz
    from jsonb_array_elements(p_snapshot->'orders') o;

  perform setval(pg_get_serial_sequence('public.suppliers','id'), greatest(coalesce((select max(id) from public.suppliers),0)+1,1), false);
  perform setval(pg_get_serial_sequence('public.materials','id'), greatest(coalesce((select max(id) from public.materials),0)+1,1), false);
  perform setval(pg_get_serial_sequence('public.orders','id'), greatest(coalesce((select max(id) from public.orders),0)+1,1), false);
  select count(*) into v_supplier_count from public.suppliers;
  select count(*) into v_material_count from public.materials;
  select count(*) into v_order_count from public.orders;
  return jsonb_build_object('suppliers',v_supplier_count,'materials',v_material_count,'orders',v_order_count);
end;
$$;
revoke all on function public.restore_snapshot(jsonb) from public;
revoke all on function public.restore_snapshot(jsonb) from anon;
grant execute on function public.restore_snapshot(jsonb) to authenticated;

do $$ begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='suppliers') then alter publication supabase_realtime add table public.suppliers; end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='materials') then alter publication supabase_realtime add table public.materials; end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='orders') then alter publication supabase_realtime add table public.orders; end if;
end $$;

commit;

-- 创建登录用户后，在 SQL Editor 核对 auth.users 的 UUID，再手工授予管理员：
-- insert into public.profiles (user_id,is_admin) values ('确认过的用户UUID',true)
-- on conflict (user_id) do update set is_admin=excluded.is_admin;
